In [7]:
import pandas as pd
import pickle
import joblib
# df = pd.read_pickle('poses/results/demo_TIGER_WOODS_THqn7IjaiEY_1c3e5a96-37ee-4fe4-8df9-1c97cea2cf67.pkl')

# print(df.head())

In [8]:
x = joblib.load('poses/results/demo_TIGER_WOODS_THqn7IjaiEY_1c3e5a96-37ee-4fe4-8df9-1c97cea2cf67.pkl')

print(x['/home/daniel/development/csc2626/final-project/golfdb/data/poses//_DEMO/TIGER_WOODS_THqn7IjaiEY_1c3e5a96-37ee-4fe4-8df9-1c97cea2cf67/img/000001.jpg']['smpl'])

[{'global_orient': array([[[ 0.4605741 ,  0.14099394,  0.87635165],
        [-0.13967428, -0.96349114,  0.2284206 ],
        [ 0.87656295, -0.2276084 , -0.42406583]]], dtype=float32), 'body_pose': array([[[ 0.9917079 , -0.12848052,  0.00287702],
        [ 0.11903502,  0.9267777 ,  0.3562495 ],
        [-0.04843748, -0.35295296,  0.9343865 ]],

       [[ 0.9918545 ,  0.12487186,  0.02513599],
        [-0.12499274,  0.916153  ,  0.38084185],
        [ 0.02452803, -0.38088146,  0.9242986 ]],

       [[ 0.9966353 ,  0.0787034 ,  0.02288621],
        [-0.05303569,  0.8321287 , -0.55204076],
        [-0.06249176,  0.5489695 ,  0.83350295]],

       [[ 0.99836105, -0.01921415, -0.0539069 ],
        [ 0.00457716,  0.9657448 , -0.2594532 ],
        [ 0.05704549,  0.25878125,  0.9642499 ]],

       [[ 0.9915284 ,  0.04208705,  0.12288226],
        [-0.00949147,  0.9669973 , -0.25460958],
        [-0.12954259,  0.25128633,  0.9592048 ]],

       [[ 0.9978754 ,  0.05253947,  0.03852541],
        [

In [9]:
joints = x['/home/daniel/development/csc2626/final-project/golfdb/data/poses//_DEMO/TIGER_WOODS_THqn7IjaiEY_1c3e5a96-37ee-4fe4-8df9-1c97cea2cf67/img/000001.jpg']['3d_joints']

In [10]:
import plotly.graph_objects as go

BONE_CONNECTIONS = {
    'nose_to_neck': [0, 1],
    'neck_to_rshoulder': [1, 2],
    'rshoulder_to_relbow': [2, 3],
    'relbow_to_rwrist': [3, 4],
    'neck_to_lshoulder': [1, 5],
    'lshoulder_to_lelbow': [5, 6],
    'lelbow_to_lwrist': [6, 7],
    'neck_to_midhip': [1, 8],
    'midhip_to_rhip': [8, 9],
    'rhip_to_rknee': [9, 10],
    'rknee_to_rankle': [10, 11],
    'midhip_to_lhip': [8, 12],
    'lhip_to_lknee': [12, 13],
    'lknee_to_lankle': [13, 14],
    'nose_to_reye': [0, 15],
    'nose_to_leye': [0, 16],
    'reye_to_rear': [15, 17],
    'leye_to_lear': [16, 18],
    'lankle_to_lbigtoe': [14, 19],
    'lankle_to_lsmalltoe': [14, 20],
    'lankle_to_lheel': [14, 21],
    'rankle_to_rbigtoe': [11, 22],
    'rankle_to_rsmalltoe': [11, 23],
    'rankle_to_rheel': [11, 24],
}

# Extract the 3D joint coordinates
joints_3d = joints[0][:25]

# Create a 3D scatter plot
print(joints_3d)
print(len(joints_3d))
x_coords = [joint[0] for joint in joints_3d]
y_coords = [joint[1] for joint in joints_3d]
z_coords = [joint[2] for joint in joints_3d]
# x_coords = [1, 2, 3]
# y_coords = [4, 5, 6]
# z_coords = [7, 8, 9]

print(x_coords, y_coords, z_coords)
fig = go.Figure(data=[go.Scatter3d(
    x=x_coords,
    y=y_coords,
    z=z_coords,
    mode='markers',
    marker=dict(
        size=5,
        color=['blue' if i == 44 else 'red' for i in range(len(joints_3d))],  # Color the 45th joint in blue
    )
)])

# Add lines for each bone defined in BONE_CONNECTIONS
for bone_name, (start_joint, end_joint) in BONE_CONNECTIONS.items():
    fig.add_trace(go.Scatter3d(
        x=[joints_3d[start_joint][0], joints_3d[end_joint][0]],
        y=[joints_3d[start_joint][1], joints_3d[end_joint][1]],
        z=[joints_3d[start_joint][2], joints_3d[end_joint][2]],
        mode='lines',
        line=dict(color='blue', width=2),
        name=bone_name
    ))



# Set labels
fig.update_layout(
    scene=dict(
        xaxis_title='X',
        yaxis_title='Y',
        zaxis_title='Z'
    )
)

# Show the plot
fig.show()


[[ 0.43687135 -0.5813496  -0.16429722]
 [ 0.25426435 -0.6080713  -0.10755011]
 [ 0.1941773  -0.50144124 -0.24860758]
 [ 0.1893078  -0.24210232 -0.26919386]
 [ 0.250584    0.00486651 -0.21073762]
 [ 0.28295812 -0.52876824  0.06108666]
 [ 0.2645902  -0.2732781   0.13643454]
 [ 0.25845423 -0.03920341  0.03637706]
 [-0.00181581 -0.22008194  0.0264163 ]
 [-0.04983216 -0.12498005 -0.0091709 ]
 [-0.01797044  0.2632233  -0.06564137]
 [-0.0911397   0.66561294 -0.02909748]
 [ 0.01015145 -0.14351982  0.11045104]
 [ 0.1141456   0.21468315  0.21025729]
 [ 0.0745897   0.6006846   0.34403718]
 [ 0.4258828  -0.6313965  -0.19937763]
 [ 0.44732    -0.63502777 -0.1360642 ]
 [ 0.33514175 -0.6796278  -0.21642181]
 [ 0.3817982  -0.6876758  -0.07631441]
 [ 0.25306472  0.6878569   0.29350886]
 [ 0.23225605  0.6676012   0.37227175]
 [ 0.02038204  0.6250005   0.38096917]
 [ 0.07721041  0.75665736 -0.10601286]
 [-0.00157204  0.7569655  -0.14520329]
 [-0.15061742  0.6996273  -0.00098398]]
25
[np.float32(0.4368713

In [11]:
JOINT_NAMES = [
# 25 OpenPose joints (in the order provided by OpenPose)
'OP Nose',
'OP Neck',
'OP RShoulder',
'OP RElbow',
'OP RWrist',
'OP LShoulder',
'OP LElbow',
'OP LWrist',
'OP MidHip',
'OP RHip',
'OP RKnee',
'OP RAnkle',
'OP LHip',
'OP LKnee',
'OP LAnkle',
'OP REye',
'OP LEye',
'OP REar',
'OP LEar',
'OP LBigToe',
'OP LSmallToe',
'OP LHeel',
'OP RBigToe',
'OP RSmallToe',
'OP RHeel',
# 24 Ground Truth joints (superset of joints from different datasets)
'Right Ankle',
'Right Knee',
'Right Hip',
'Left Hip',
'Left Knee',
'Left Ankle',
'Right Wrist',
'Right Elbow',
'Right Shoulder',
'Left Shoulder',
'Left Elbow',
'Left Wrist',
'Neck (LSP)',
'Top of Head (LSP)',
'Pelvis (MPII)',
'Thorax (MPII)',
'Spine (H36M)',
'Jaw (H36M)',
'Head (H36M)',
'ROOT'
]
print(len(JOINT_NAMES))

45


In [16]:
import numpy as np

def compute_all_joint_angles(pose_array):
    """
    Compute all joint angles from OpenPose joint positions to match Isaac Sim format
    
    Args:
        pose_array: numpy array of shape (45, 3) containing joint positions
        
    Returns:
        numpy array of shape (21,) matching initial_positions format
    """
    # OpenPose indices
    NECK_IDX = 1        # OP Neck
    R_SHOULDER_IDX = 2  # OP RShoulder
    R_ELBOW_IDX = 3    # OP RElbow
    R_WRIST_IDX = 4    # OP RWrist
    L_SHOULDER_IDX = 5  # OP LShoulder
    L_ELBOW_IDX = 6    # OP LElbow
    L_WRIST_IDX = 7    # OP LWrist
    MID_HIP_IDX = 8    # OP MidHip
    R_HIP_IDX = 9      # OP RHip
    R_KNEE_IDX = 10    # OP RKnee
    R_ANKLE_IDX = 11   # OP RAnkle
    L_HIP_IDX = 12     # OP LHip
    L_KNEE_IDX = 13    # OP LKnee
    L_ANKLE_IDX = 14   # OP LAnkle
    R_FOOT_IDX = 22    # OP RBigToe
    L_FOOT_IDX = 19    # OP LBigToe
    
    def compute_waist_angles(neck, mid_hip):
        # Calculate waist bend forward/backward and side-to-side
        spine_vector = neck - mid_hip
        spine_vector = spine_vector / np.linalg.norm(spine_vector)
        
        # Forward/backward bend (in sagittal plane)
        sagittal_angle = np.arctan2(spine_vector[2], spine_vector[1])
        
        # Side-to-side bend (in coronal plane)
        coronal_angle = np.arctan2(spine_vector[0], spine_vector[1])
        
        return sagittal_angle / np.pi, coronal_angle / np.pi
    
    def compute_arm_angles(shoulder_idx, elbow_idx, wrist_idx):
        shoulder_pos = pose_array[shoulder_idx]
        elbow_pos = pose_array[elbow_idx]
        wrist_pos = pose_array[wrist_idx]
        
        spine = pose_array[NECK_IDX] - pose_array[MID_HIP_IDX]
        shoulder_line = pose_array[R_SHOULDER_IDX] - pose_array[L_SHOULDER_IDX]
        coronal_normal = np.cross(spine, shoulder_line)
        coronal_normal = coronal_normal / np.linalg.norm(coronal_normal)
        sagittal_normal = np.cross(coronal_normal, spine)
        # Upper arm angles
        upper_arm = elbow_pos - shoulder_pos
        upper_arm = upper_arm / np.linalg.norm(upper_arm)
        
        # Abduction angle relative to coronal plane
        abduction = np.arccos(np.dot(upper_arm, coronal_normal))
        if np.dot(upper_arm, shoulder_line) < 0:  # Check if arm is moving away from body
            abduction = -abduction
            
        # Flexion angle
        flexion = np.arccos(np.dot(upper_arm, sagittal_normal))
        # sagittal_projection = np.array([upper_arm[2], upper_arm[1]])
        # sagittal_projection = sagittal_projection / np.linalg.norm(sagittal_projection)
        # flexion = np.arccos(np.dot(sagittal_projection, [0, 1]))
        # if upper_arm[2] < 0:
        #     flexion = -flexion
            
        # Lower arm angle (elbow)
        forearm = wrist_pos - elbow_pos
        upper_arm = elbow_pos - shoulder_pos
        elbow_angle = np.arccos(np.dot(forearm, upper_arm) / 
                               (np.linalg.norm(forearm) * np.linalg.norm(upper_arm)))
        
        return abduction, flexion, (elbow_angle)
    
    def compute_leg_angles(hip_idx, knee_idx, ankle_idx, foot_idx):
        hip_pos = pose_array[hip_idx]
        knee_pos = pose_array[knee_idx]
        ankle_pos = pose_array[ankle_idx]
        foot_pos = pose_array[foot_idx]
        
        # Thigh angles
        thigh = knee_pos - hip_pos
        thigh = thigh / np.linalg.norm(thigh)
        
        # Calculate three rotation angles for thigh
        thigh_x = np.arctan2(thigh[2], thigh[1])  # forward/backward
        thigh_y = np.arctan2(thigh[0], thigh[1])  # side-to-side
        thigh_z = np.arctan2(thigh[0], thigh[2])  # rotation
        
        # Knee angle
        shank = ankle_pos - knee_pos
        knee_angle = np.arccos(np.dot(thigh, shank) /
                             (np.linalg.norm(thigh) * np.linalg.norm(shank)))
        
        # Foot angles
        foot = foot_pos - ankle_pos
        foot_pitch = np.arctan2(foot[2], foot[1])  # up/down
        foot_roll = np.arctan2(foot[0], foot[1])   # inversion/eversion
        
        return (thigh_x / np.pi, thigh_y / np.pi, thigh_z / np.pi, 
                knee_angle / np.pi, foot_pitch / np.pi, foot_roll / np.pi)
    
    # Calculate all angles
    waist_sagittal, waist_coronal = compute_waist_angles(
        pose_array[NECK_IDX], pose_array[MID_HIP_IDX])
    
    r_abd, r_flex, r_elbow = compute_arm_angles(
        R_SHOULDER_IDX, R_ELBOW_IDX, R_WRIST_IDX)
    l_abd, l_flex, l_elbow = compute_arm_angles(
        L_SHOULDER_IDX, L_ELBOW_IDX, L_WRIST_IDX)
    
    pelvis_angle = np.arctan2(
        pose_array[R_HIP_IDX][0] - pose_array[L_HIP_IDX][0],
        pose_array[R_HIP_IDX][2] - pose_array[L_HIP_IDX][2]) / np.pi
    
    r_thigh_x, r_thigh_y, r_thigh_z, r_knee, r_foot_pitch, r_foot_roll = compute_leg_angles(
        R_HIP_IDX, R_KNEE_IDX, R_ANKLE_IDX, R_FOOT_IDX)
    l_thigh_x, l_thigh_y, l_thigh_z, l_knee, l_foot_pitch, l_foot_roll = compute_leg_angles(
        L_HIP_IDX, L_KNEE_IDX, L_ANKLE_IDX, L_FOOT_IDX)
    
    # Assemble in the same order as initial_positions
    return np.array([
        waist_coronal,  # lower_waist
        waist_sagittal,   # lower_waist
        r_abd,          # right_upper_arm
        r_flex,         # right_upper_arm
        l_abd,          # left_upper_arm
        l_flex,         # left_upper_arm
        pelvis_angle,   # pelvis
        r_elbow,        # right_lower_arm
        l_elbow,        # left_lower_arm
        r_thigh_x,      # right_thigh: x
        r_thigh_y,      # right_thigh: y
        r_thigh_z,      # right_thigh: z
        l_thigh_x,      # left_thigh: x
        l_thigh_y,      # left_thigh: y
        l_thigh_z,      # left_thigh: z
        r_knee,         # right_knee
        l_knee,         # left_knee
        r_foot_pitch,   # right_foot
        r_foot_roll,    # right_foot
        l_foot_pitch,   # left_foot
        l_foot_roll,    # left_foot
    ])

# Example usage:
# pose_data = np.random.rand(45, 3)  # Your pose data here
# joint_angles = compute_all_joint_angles(pose_data)

In [15]:
joint_angles = compute_all_joint_angles(joints_3d)
print(joint_angles)

[ 0.8143025  -0.89417243  0.30267698  0.46815178 -0.3498035   0.519223
 -0.85204905 -0.8723765  -0.77993596 -0.04598082  0.0260668   0.836486
  0.08649698  0.08993983  0.25654003  0.11140303  0.11913639 -0.22328617
  0.34219608 -0.16721205  0.3553766 ]
