In [1]:
import pandas as pd
import pickle
import joblib
# df = pd.read_pickle('poses/results/demo_TIGER_WOODS_THqn7IjaiEY_1c3e5a96-37ee-4fe4-8df9-1c97cea2cf67.pkl')

# print(df.head())

In [2]:
x = joblib.load('poses/results/demo_TIGER_WOODS_THqn7IjaiEY_1c3e5a96-37ee-4fe4-8df9-1c97cea2cf67.pkl')

print(x.keys())

dict_keys(['/home/daniel/development/csc2626/final-project/golfdb/data/poses//_DEMO/TIGER_WOODS_THqn7IjaiEY_1c3e5a96-37ee-4fe4-8df9-1c97cea2cf67/img/000001.jpg', '/home/daniel/development/csc2626/final-project/golfdb/data/poses//_DEMO/TIGER_WOODS_THqn7IjaiEY_1c3e5a96-37ee-4fe4-8df9-1c97cea2cf67/img/000002.jpg', '/home/daniel/development/csc2626/final-project/golfdb/data/poses//_DEMO/TIGER_WOODS_THqn7IjaiEY_1c3e5a96-37ee-4fe4-8df9-1c97cea2cf67/img/000003.jpg', '/home/daniel/development/csc2626/final-project/golfdb/data/poses//_DEMO/TIGER_WOODS_THqn7IjaiEY_1c3e5a96-37ee-4fe4-8df9-1c97cea2cf67/img/000004.jpg', '/home/daniel/development/csc2626/final-project/golfdb/data/poses//_DEMO/TIGER_WOODS_THqn7IjaiEY_1c3e5a96-37ee-4fe4-8df9-1c97cea2cf67/img/000005.jpg', '/home/daniel/development/csc2626/final-project/golfdb/data/poses//_DEMO/TIGER_WOODS_THqn7IjaiEY_1c3e5a96-37ee-4fe4-8df9-1c97cea2cf67/img/000006.jpg', '/home/daniel/development/csc2626/final-project/golfdb/data/poses//_DEMO/TIGER_WOOD

In [3]:
joints = x['/home/daniel/development/csc2626/final-project/golfdb/data/poses//_DEMO/TIGER_WOODS_THqn7IjaiEY_1c3e5a96-37ee-4fe4-8df9-1c97cea2cf67/img/000001.jpg']['3d_joints']

In [15]:
import plotly.graph_objects as go

BONE_CONNECTIONS = {
    'nose_to_neck': [0, 1],
    'neck_to_rshoulder': [1, 2],
    'rshoulder_to_relbow': [2, 3],
    'relbow_to_rwrist': [3, 4],
    'neck_to_lshoulder': [1, 5],
    'lshoulder_to_lelbow': [5, 6],
    'lelbow_to_lwrist': [6, 7],
    'neck_to_midhip': [1, 8],
    'midhip_to_rhip': [8, 9],
    'rhip_to_rknee': [9, 10],
    'rknee_to_rankle': [10, 11],
    'midhip_to_lhip': [8, 12],
    'lhip_to_lknee': [12, 13],
    'lknee_to_lankle': [13, 14],
    'nose_to_reye': [0, 15],
    'nose_to_leye': [0, 16],
    'reye_to_rear': [15, 17],
    'leye_to_lear': [16, 18],
    'lankle_to_lbigtoe': [14, 19],
    'lankle_to_lsmalltoe': [14, 20],
    'lankle_to_lheel': [14, 21],
    'rankle_to_rbigtoe': [11, 22],
    'rankle_to_rsmalltoe': [11, 23],
    'rankle_to_rheel': [11, 24],
}

# Extract the 3D joint coordinates
joints_3d = joints[0][:25]

# Create a 3D scatter plot
print(joints_3d)
print(len(joints_3d))
x_coords = [joint[0] for joint in joints_3d]
y_coords = [joint[1] for joint in joints_3d]
z_coords = [joint[2] for joint in joints_3d]
# x_coords = [1, 2, 3]
# y_coords = [4, 5, 6]
# z_coords = [7, 8, 9]

print(x_coords, y_coords, z_coords)
fig = go.Figure(data=[go.Scatter3d(
    x=x_coords,
    y=y_coords,
    z=z_coords,
    mode='markers',
    marker=dict(
        size=5,
        color=['blue' if i == 44 else 'red' for i in range(len(joints_3d))],  # Color the 45th joint in blue
    )
)])

# Add lines for each bone defined in BONE_CONNECTIONS
for bone_name, (start_joint, end_joint) in BONE_CONNECTIONS.items():
    fig.add_trace(go.Scatter3d(
        x=[joints_3d[start_joint][0], joints_3d[end_joint][0]],
        y=[joints_3d[start_joint][1], joints_3d[end_joint][1]],
        z=[joints_3d[start_joint][2], joints_3d[end_joint][2]],
        mode='lines',
        line=dict(color='blue', width=2),
        name=bone_name
    ))



# Set labels
fig.update_layout(
    scene=dict(
        xaxis_title='X',
        yaxis_title='Y',
        zaxis_title='Z'
    )
)

# Show the plot
fig.show()


[[ 0.43687135 -0.5813496  -0.16429722]
 [ 0.25426435 -0.6080713  -0.10755011]
 [ 0.1941773  -0.50144124 -0.24860758]
 [ 0.1893078  -0.24210232 -0.26919386]
 [ 0.250584    0.00486651 -0.21073762]
 [ 0.28295812 -0.52876824  0.06108666]
 [ 0.2645902  -0.2732781   0.13643454]
 [ 0.25845423 -0.03920341  0.03637706]
 [-0.00181581 -0.22008194  0.0264163 ]
 [-0.04983216 -0.12498005 -0.0091709 ]
 [-0.01797044  0.2632233  -0.06564137]
 [-0.0911397   0.66561294 -0.02909748]
 [ 0.01015145 -0.14351982  0.11045104]
 [ 0.1141456   0.21468315  0.21025729]
 [ 0.0745897   0.6006846   0.34403718]
 [ 0.4258828  -0.6313965  -0.19937763]
 [ 0.44732    -0.63502777 -0.1360642 ]
 [ 0.33514175 -0.6796278  -0.21642181]
 [ 0.3817982  -0.6876758  -0.07631441]
 [ 0.25306472  0.6878569   0.29350886]
 [ 0.23225605  0.6676012   0.37227175]
 [ 0.02038204  0.6250005   0.38096917]
 [ 0.07721041  0.75665736 -0.10601286]
 [-0.00157204  0.7569655  -0.14520329]
 [-0.15061742  0.6996273  -0.00098398]]
25
[np.float32(0.4368713

In [12]:
JOINT_NAMES = [
# 25 OpenPose joints (in the order provided by OpenPose)
'OP Nose',
'OP Neck',
'OP RShoulder',
'OP RElbow',
'OP RWrist',
'OP LShoulder',
'OP LElbow',
'OP LWrist',
'OP MidHip',
'OP RHip',
'OP RKnee',
'OP RAnkle',
'OP LHip',
'OP LKnee',
'OP LAnkle',
'OP REye',
'OP LEye',
'OP REar',
'OP LEar',
'OP LBigToe',
'OP LSmallToe',
'OP LHeel',
'OP RBigToe',
'OP RSmallToe',
'OP RHeel',
# 24 Ground Truth joints (superset of joints from different datasets)
'Right Ankle',
'Right Knee',
'Right Hip',
'Left Hip',
'Left Knee',
'Left Ankle',
'Right Wrist',
'Right Elbow',
'Right Shoulder',
'Left Shoulder',
'Left Elbow',
'Left Wrist',
'Neck (LSP)',
'Top of Head (LSP)',
'Pelvis (MPII)',
'Thorax (MPII)',
'Spine (H36M)',
'Jaw (H36M)',
'Head (H36M)',
'ROOT'
]
print(len(JOINT_NAMES))

45
